# Generated by Django 3.1.1 on 2020-10-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=100)),
                ('trackingid', models.CharField(max_length=100)),
                ('courierservice', models.TextField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('statusdate', models.DateTimeField()),
                ('deliverydate', models.DateTimeField()),
            ],
        ),
    ]
