# Generated by Django 3.1.1 on 2020-10-25 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20201010_1426'),
        ('delivery', '0002_auto_20201010_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='courierservice',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('W1', 'Preparing'), ('W2', 'Ready to dispatch'), ('W3', 'Dispatched'), ('W4', 'Delivered')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='statusdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='trackingid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
