# Generated by Django 3.1.1 on 2020-11-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20201025_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliverydate',
            field=models.DateTimeField(),
        ),
    ]
