# Generated by Django 3.1.1 on 2020-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='document/')),
                ('docType', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
