# Generated by Django 3.1.1 on 2020-11-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20201025_1730'),
        ('contactus', '0002_auto_20201017_0902'),
    ]

    operations = [
    ]
