# Generated by Django 3.1.1 on 2020-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Customerid',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
