# Generated by Django 3.1.1 on 2020-10-10 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_address_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='countryid',
            field=models.CharField(choices=[('India', 'India'), ('UK', 'UK')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='Customerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressline2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='instructions',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(choices=[('India', 'India'), ('UK', 'UK')], max_length=100)),
                ('statename', models.ManyToManyField(to='address.States')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.states'),
        ),
    ]
