# Generated by Django 3.1.1 on 2020-10-11 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0003_auto_20201010_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Customerid',
        ),
        migrations.AddField(
            model_name='address',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressline1',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='countryid',
            field=models.CharField(choices=[('India', 'India'), ('UK', 'UK')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='fullname',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phonenumber',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.states'),
        ),
    ]
