# Generated by Django 3.1.1 on 2020-10-31 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0004_auto_20201025_1812'),
        ('products', '0007_auto_20201031_2214'),
        ('documents', '0001_initial'),
        ('orders', '0004_auto_20201025_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.FloatField(null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documents')),
                ('cartid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('photoid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photos')),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
