# Generated by Django 3.1.1 on 2020-11-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201025_1730'),
        ('photos', '0004_auto_20201025_1812'),
        ('documents', '0001_initial'),
        ('cart', '0002_auto_20201101_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='documentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documents'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='photoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photos'),
        ),
    ]
